name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Run this action when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/py-hello:latest .

      # Add a specific tag to the Docker image
      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/py-hello:latest ${{ secrets.DOCKER_USERNAME }}/py-hello:24ds1000046

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/py-hello:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/py-hello:24ds1000046
